[package]
name = "diplos"
version = "1.1.0"
edition = "2018"
authors = ["tricked!"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "diplo"
