# This is a basic workflow to generate release artifacts for the full repo contents

name: Release

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - run: ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE"
      # - uses: actions/checkout@v2
